// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhZIiULP4RE3WLnO19jTVwnhQes6Uca4A',
    appId: '1:359376966581:web:6147000fb7c469bb463ffc',
    messagingSenderId: '359376966581',
    projectId: 'instagram-clone-60793',
    authDomain: 'instagram-clone-60793.firebaseapp.com',
    storageBucket: 'instagram-clone-60793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMtJK_ZI-YQNWnFEMPmlnfu9OYvnoSDsU',
    appId: '1:359376966581:android:10f4210c11fa91bb463ffc',
    messagingSenderId: '359376966581',
    projectId: 'instagram-clone-60793',
    storageBucket: 'instagram-clone-60793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiiCPy-jrM1bvg6HDnqtRyA7zSgfvhP24',
    appId: '1:359376966581:ios:20466182274cafcb463ffc',
    messagingSenderId: '359376966581',
    projectId: 'instagram-clone-60793',
    storageBucket: 'instagram-clone-60793.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
